export { default as AboutSection } from './AboutSection'
export { default as ContactSection } from './ContactSection'
export { default as FooterSection } from './FooterSection'
export { default as HeroSection } from './HeroSection'
export { default as OfferSection } from './OfferSection'
export { default as ProjectSection } from './ProjectSection'
export { default as SkillSection } from './SkillSection'
